
project_id = "pvesgvkyiaqmsudmmtkc"

[functions.quote-approval-automation]
verify_jwt = false

[functions.send-quote-confirmation-email]
verify_jwt = false

[functions.auth-mobile]
verify_jwt = false

[functions.customers-mobile]
verify_jwt = true

[functions.stripe-config-test]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = true
