import { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { text, targetLanguage = 'en' } = req.body;

  if (!text) {
    return res.status(400).json({ error: 'Text is required' });
  }

  try {
    // For now, we'll use a simple translation service
    // You can replace this with Google Translate API, DeepL, or other services
    
    // Simple Dutch to English translation mapping (basic examples)
    const translations: Record<string, string> = {
      'hallo': 'hello',
      'dank je': 'thank you',
      'ja': 'yes',
      'nee': 'no',
      'goed': 'good',
      'slecht': 'bad',
      'project': 'project',
      'klant': 'client',
      'tijd': 'time',
      'werk': 'work',
      'vandaag': 'today',
      'morgen': 'tomorrow',
      'gisteren': 'yesterday',
      'chat': 'chat',
      'bericht': 'message',
      'foto': 'photo',
      'video': 'video',
      'audio': 'audio',
      'bestand': 'file',
      'upload': 'upload',
      'download': 'download',
      'verstuur': 'send',
      'ontvang': 'receive',
      'online': 'online',
      'offline': 'offline',
      'actief': 'active',
      'inactief': 'inactive',
      'administrator': 'administrator',
      'administratie': 'administration',
      'installateur': 'installer',
      'monteur': 'technician',
      'gebruiker': 'user',
      'profiel': 'profile',
      'instellingen': 'settings',
      'uitloggen': 'logout',
      'inloggen': 'login',
      'wachtwoord': 'password',
      'email': 'email',
      'telefoon': 'phone',
      'adres': 'address',
      'naam': 'name',
      'achternaam': 'surname',
      'voornaam': 'first name',
      'bedrijf': 'company',
      'organisatie': 'organization',
      'afdeling': 'department',
      'functie': 'function',
      'rol': 'role',
      'rechten': 'rights',
      'toegang': 'access',
      'beheer': 'management',
      'overzicht': 'overview',
      'lijst': 'list',
      'tabel': 'table',
      'grafiek': 'chart',
      'rapport': 'report',
      'export': 'export',
      'import': 'import',
      'synchronisatie': 'synchronization',
      'backup': 'backup',
      'herstel': 'restore',
      'update': 'update',
      'upgrade': 'upgrade',
      'versie': 'version',
      'revisie': 'revision',
      'wijziging': 'change',
      'aanpassing': 'adjustment',
      'configuratie': 'configuration',
      'instelling': 'setting',
      'optie': 'option',
      'keuze': 'choice',
      'selectie': 'selection',
      'filter': 'filter',
      'sorteren': 'sort',
      'zoeken': 'search',
      'zoekopdracht': 'search query',
      'resultaat': 'result',
      'uitkomst': 'outcome',
      'conclusie': 'conclusion',
      'samenvatting': 'summary',
      'overzicht': 'overview',
      'details': 'details',
      'informatie': 'information',
      'gegevens': 'data',
      'database': 'database',
      'server': 'server',
      'client': 'client',
      'netwerk': 'network',
      'verbinding': 'connection',
      'connectie': 'connection',
      'sessie': 'session',
      'login': 'login',
      'logout': 'logout',
      'authenticatie': 'authentication',
      'autorisatie': 'authorization',
      'beveiliging': 'security',
      'privacy': 'privacy',
      'toestemming': 'permission',
      'machtiging': 'authorization',
      'rechten': 'rights',
      'privileges': 'privileges',
      'toegang': 'access',
      'beheer': 'management',
      'administratie': 'administration',
      'supervisor': 'supervisor',
      'manager': 'manager',
      'directeur': 'director',
      'ceo': 'ceo',
      'cto': 'cto',
      'cfo': 'cfo',
      'cmo': 'cmo',
      'hr': 'hr',
      'it': 'it',
      'finance': 'finance',
      'sales': 'sales',
      'marketing': 'marketing',
      'support': 'support',
      'service': 'service',
      'onderhoud': 'maintenance',
      'reparatie': 'repair',
      'installatie': 'installation',
      'configuratie': 'configuration',
      'setup': 'setup',
      'installatie': 'installation',
      'implementatie': 'implementation',
      'deployment': 'deployment',
      'rollout': 'rollout',
      'migratie': 'migration',
      'upgrade': 'upgrade',
      'downgrade': 'downgrade',
      'patch': 'patch',
      'hotfix': 'hotfix',
      'bugfix': 'bugfix',
      'feature': 'feature',
      'functionaliteit': 'functionality',
      'mogelijkheid': 'capability',
      'optie': 'option',
      'keuze': 'choice',
      'alternatief': 'alternative',
      'vervanging': 'replacement',
      'substitutie': 'substitution',
      'equivalent': 'equivalent',
      'gelijkwaardig': 'equivalent',
      'vergelijkbaar': 'comparable',
      'soortgelijk': 'similar',
      'identiek': 'identical',
      'exact': 'exact',
      'precies': 'precise',
      'nauwkeurig': 'accurate',
      'correct': 'correct',
      'juist': 'right',
      'waar': 'true',
      'onwaar': 'false',
      'fout': 'error',
      'foutmelding': 'error message',
      'waarschuwing': 'warning',
      'melding': 'notification',
      'bericht': 'message',
      'informatie': 'information',
      'details': 'details',
      'specificaties': 'specifications',
      'vereisten': 'requirements',
      'criteria': 'criteria',
      'standaarden': 'standards',
      'richtlijnen': 'guidelines',
      'procedures': 'procedures',
      'processen': 'processes',
      'workflows': 'workflows',
      'stappen': 'steps',
      'fasen': 'phases',
      'etappen': 'stages',
      'niveaus': 'levels',
      'lagen': 'layers',
      'componenten': 'components',
      'modules': 'modules',
      'pakketten': 'packages',
      'bibliotheken': 'libraries',
      'frameworks': 'frameworks',
      'tools': 'tools',
      'gereedschap': 'tools',
      'instrumenten': 'instruments',
      'apparaten': 'devices',
      'machines': 'machines',
      'systemen': 'systems',
      'platforms': 'platforms',
      'omgevingen': 'environments',
      'infrastructuren': 'infrastructures',
      'architecturen': 'architectures',
      'ontwerpen': 'designs',
      'modellen': 'models',
      'templates': 'templates',
      'sjablonen': 'templates',
      'patronen': 'patterns',
      'structuren': 'structures',
      'formaten': 'formats',
      'types': 'types',
      'categorieën': 'categories',
      'klassen': 'classes',
      'groepen': 'groups',
      'sets': 'sets',
      'collecties': 'collections',
      'arrays': 'arrays',
      'lijsten': 'lists',
      'tabellen': 'tables',
      'databases': 'databases',
      'bestanden': 'files',
      'documenten': 'documents',
      'records': 'records',
      'entries': 'entries',
      'items': 'items',
      'objecten': 'objects',
      'entiteiten': 'entities',
      'instanties': 'instances',
      'exemplaren': 'copies',
      'versies': 'versions',
      'releases': 'releases',
      'builds': 'builds',
      'compilaties': 'compilations',
      'assemblies': 'assemblies',
      'executables': 'executables',
      'binaries': 'binaries',
      'libraries': 'libraries',
      'dependencies': 'dependencies',
      'afhankelijkheden': 'dependencies',
      'requirements': 'requirements',
      'vereisten': 'requirements',
      'prerequisites': 'prerequisites',
      'voorwaarden': 'conditions',
      'condities': 'conditions',
      'regels': 'rules',
      'beperkingen': 'limitations',
      'restricties': 'restrictions',
      'constraints': 'constraints',
      'validaties': 'validations',
      'controles': 'checks',
      'tests': 'tests',
      'testen': 'testing',
      'verificaties': 'verifications',
      'validaties': 'validations',
      'certificaties': 'certifications',
      'accreditatie': 'accreditation',
      'kwalificatie': 'qualification',
      'competentie': 'competence',
      'vaardigheid': 'skill',
      'expertise': 'expertise',
      'kennis': 'knowledge',
      'ervaring': 'experience',
      'praktijk': 'practice',
      'theorie': 'theory',
      'concept': 'concept',
      'idee': 'idea',
      'oplossing': 'solution',
      'probleem': 'problem',
      'uitdaging': 'challenge',
      'kans': 'opportunity',
      'mogelijkheid': 'possibility',
      'potentieel': 'potential',
      'capaciteit': 'capacity',
      'vermogen': 'ability',
      'kracht': 'power',
      'energie': 'energy',
      'bron': 'source',
      'resource': 'resource',
      'middel': 'means',
      'tool': 'tool',
      'instrument': 'instrument',
      'apparaat': 'device',
      'machine': 'machine',
      'systeem': 'system',
      'platform': 'platform',
      'omgeving': 'environment',
      'infrastructuur': 'infrastructure',
      'architectuur': 'architecture',
      'ontwerp': 'design',
      'model': 'model',
      'template': 'template',
      'sjabloon': 'template',
      'patroon': 'pattern',
      'structuur': 'structure',
      'format': 'format',
      'type': 'type',
      'categorie': 'category',
      'klasse': 'class',
      'groep': 'group',
      'set': 'set',
      'collectie': 'collection',
      'array': 'array',
      'lijst': 'list',
      'tabel': 'table',
      'database': 'database',
      'bestand': 'file',
      'document': 'document',
      'record': 'record',
      'entry': 'entry',
      'item': 'item',
      'object': 'object',
      'entiteit': 'entity',
      'instantie': 'instance',
      'exemplaar': 'copy',
      'versie': 'version',
      'release': 'release',
      'build': 'build',
      'compilatie': 'compilation',
      'assembly': 'assembly',
      'executable': 'executable',
      'binary': 'binary',
      'library': 'library',
      'dependency': 'dependency',
      'afhankelijkheid': 'dependency',
      'requirement': 'requirement',
      'vereiste': 'requirement',
      'prerequisite': 'prerequisite',
      'voorwaarde': 'condition',
      'conditie': 'condition',
      'regel': 'rule',
      'beperking': 'limitation',
      'restrictie': 'restriction',
      'constraint': 'constraint',
      'validatie': 'validation',
      'controle': 'check',
      'test': 'test',
      'verificatie': 'verification',
      'certificatie': 'certification',
      'accreditatie': 'accreditation',
      'kwalificatie': 'qualification',
      'competentie': 'competence',
      'vaardigheid': 'skill',
      'expertise': 'expertise',
      'kennis': 'knowledge',
      'ervaring': 'experience',
      'praktijk': 'practice',
      'theorie': 'theory',
      'concept': 'concept',
      'idee': 'idea',
      'oplossing': 'solution',
      'probleem': 'problem',
      'uitdaging': 'challenge',
      'kans': 'opportunity',
      'mogelijkheid': 'possibility',
      'potentieel': 'potential',
      'capaciteit': 'capacity',
      'vermogen': 'ability',
      'kracht': 'power',
      'energie': 'energy',
      'bron': 'source',
      'resource': 'resource',
      'middel': 'means'
    };

    // Simple word-by-word translation
    const words = text.toLowerCase().split(/\s+/);
    const translatedWords = words.map(word => {
      // Remove punctuation for lookup
      const cleanWord = word.replace(/[^\w]/g, '');
      return translations[cleanWord] || word;
    });

    const translatedText = translatedWords.join(' ');
    
    return res.status(200).json({
      translatedText,
      detectedLanguage: 'nl',
      confidence: 0.8
    });
  } catch (error) {
    console.error('Translation error:', error);
    return res.status(500).json({ error: 'Translation failed' });
  }
}
