// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvesgvkyiaqmsudmmtkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZXNndmt5aWFxbXN1ZG1tdGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjI5MjIsImV4cCI6MjA2NDAzODkyMn0.Z-0t4zz2WyTiLaUIRPZzwxx9YtDiEe457X6RgQOXmU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Persist session in localStorage for automatic login after refresh
    autoRefreshToken: true, // Automatically refresh access token using refresh token (7 day expiry)
    detectSessionInUrl: true, // Detect session from URL for OAuth/magic links
    storage: typeof window !== 'undefined' ? window.localStorage : undefined, // Use localStorage for session persistence
    storageKey: 'supabase.auth.token', // Custom storage key for session data
    flowType: 'pkce', // Use PKCE flow for better security
    debug: process.env.NODE_ENV === 'development', // Enable debug logging in development
  },
});